create database Enterprise;

use Enterprise;

CREATE TABLE Department (
	DEPARTMENT_ID INT
		CONSTRAINT pk_DEPARTMENT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(40)
)

CREATE TABLE PROJECTS(
	PROJECT_ID INT
		CONSTRAINT pk_PROJECTS PRIMARY KEY,
	PROJECT_NAME VARCHAR(50)
);

CREATE TABLE Employees(
	EMPLOYEE_ID INT 
		CONSTRAINT pk_EMPLOYEES PRIMARY KEY,
	F_NAME VARCHAR(20),
	L_NAME VARCHAR(30),
	DEPARTMENT_ID INT
		CONSTRAINT fk_DEPARTMENT_ID FOREIGN KEY(DEPARTMENT_ID)
		REFERENCES Department(DEPARTMENT_ID),
	IDENTIFICATION_CARD VARCHAR(50) UNIQUE
	    CONSTRAINT CHK_CedulaFormato CHECK (
        IDENTIFICATION_CARD LIKE '[0-9]{1,2}-[0-9]{3}-[0-9]{3,4}'
    )
);

CREATE TABLE EMPLOYEE_PROJECT (
	PROJECT_ID INT
		CONSTRAINT FK_EMP_PROYC FOREIGN KEY
		REFERENCES PROJECTS(PROJECT_ID),
	EMPLOYEE_ID INT
		CONSTRAINT FK_EMP FOREIGN KEY
		REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE EMPLOYES_PHONE (
	PHONE_ID INT 
		CONSTRAINT PHONE_ID PRIMARY KEY,
	EMPLOYEE_ID INT
		CONSTRAINT FK_EMPLOYE_PHONE FOREIGN KEY
		REFERENCES EMPLOYEES(EMPLOYEE_ID),
	PHONE VARCHAR(15)
)

CREATE TABLE EMPLOYES_MAIL (
	MAIL_ID INT 
		CONSTRAINT MAIL_ID PRIMARY KEY,
	EMPLOYEE_ID INT
		CONSTRAINT FK_EMPLOYE_MAIL FOREIGN KEY
		REFERENCES EMPLOYEES(EMPLOYEE_ID),
	MAIL VARCHAR(50)
)

